Feat/styles
pawelsobkowski/spacex-fanmade-website pull request #7
Opened 2021-01-03 20:29 UTC by pawelsobkowski

Closes #3

2021-01-03 21:04 UTC, zawolanski requested changes

2021-01-03 21:04 UTC, zawolanski commented on package.json
> +    "parallelshell": "^3.0.1"
we don't use it so you can remove it

2021-01-03 21:08 UTC, pawelsobkowski commented on package.json
> +    "parallelshell": "^3.0.1"
Yes, i forgot about that.

2021-01-04 09:30 UTC, lzawistowsky approved these changes

2021-01-04 15:33 UTC, zawolanski approved these changes

2021-01-04 15:34 UTC, merged